- name: Install Java
  apt:
    name: openjdk-11-jdk  # Or whichever Java version you want to install
    state: present
  become: yes

- name: Set JAVA_HOME environment variable
  lineinfile:
    dest: /etc/environment
    line: 'JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"'
  become: yes

- name: Load environment variables
  shell: . /etc/environment
  become: yes

- name: Create a Tomcat User
  user:
    name: tomcat10

- name: Create a Tomcat Group
  group:
    name: tomcat10

- name: Create a Tomcat Directory
  file:
    path: /opt/tomcat10
    owner: tomcat10
    group: tomcat10
    mode: 755
    recurse: yes

- name: download & unarchive tomcat10 
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.19/bin/apache-tomcat-10.1.19.tar.gz
    dest: /opt/tomcat10
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Change ownership of tomcat directory
  file:
    path: /opt/tomcat10
    owner: tomcat10
    group: tomcat10
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Create empty Tomcat service file /etc/systemd/system/tomcat.service
  copy:
    src: service
    dest: /etc/systemd/system/tomcat10.service
    owner: tomcat10
    group: tomcat10
    mode: 0644

- name: Start tomcat Service
  service:
    name: tomcat10
    state: started
    daemon_reload: yes
    enabled: yes
