---

- hosts: all
  become: true
  tasks:

  - name: update repository
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apcahe
    apt:
      name: apache2
      state: latest

  - name: instal php
    apt: 
      name: libapache2-mod-php
      state: latest     


