---


- hosts: web-apps
  become: true
  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk  # Or whichever Java version you want to install
        state: present
      become: yes

    - name: Set JAVA_HOME environment variable
      lineinfile:
        dest: /etc/environment
        line: 'JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"'
      become: yes

    - name: Load environment variables
      shell: . /etc/environment
      become: yes
