---
- name: Install Apache Tomcat10 using ansible
  hosts: web-apps
  become: true
  tasks:
    - name: Update the System Packages
      apt:
        update_cache: yes

    - name: Create a Tomcat User
      user:
        name: tomcat10

    - name: Create a Tomcat Group
      group:
        name: tomcat10

    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat10
        owner: tomcat10
        group: tomcat10
        mode: 755
        recurse: yes

    - name: download & unarchive tomcat10 
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.19/bin/apache-tomcat-10.1.19.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat10
        owner: tomcat10
        group: tomcat10
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
