---

- hosts: all
  become: true
  tasks:

  - name: install apcahe and php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest  
      update_cache: yes
    

