---

- name: install apache
  hosts: all
  become: true
  pre_tasks:

  - name: update cache
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: update cache on cenOS
    tags: always
    dnf: 
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true   
  roles:
    - base

- hosts: work-station
  become: true
  roles:
    - workstations

- hosts: web-apps
  become: true
  roles: 
    - web_servers

- hosts: db-servers
  become: true
  roles: 
    - db_servers

- hosts: file-server
  become: true
  roles:
    - file_servers