---

- name: install apache
  hosts: all
  become: true
  pre_tasks:

  - name: update cache
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: update cache on cenOS
    tags: always
    dnf: 
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true   
  tasks:

  - name: add ssh keys 
    tags: always
    authorized_key: 
      user: emisha
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICeK+pv82NJPH4yS/kC80ID/Sj9mOp4tmYOV0D6f8grB New non root key"


- hosts: work-stations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install teraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        remote: 0755
        owner: root
        group: root

- hosts: web-apps
  become: true
  tasks:

  - name: install apche in server
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: install apache on CenOS
    tags: apache,php,centos
    dnf: 
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: service apache
    tags: apache
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: start httpd
    tags: apache,centos,https
    service: 
      name: httpd
      start: started
    when: ansible_distribution == "CentOS"
    
  - name: change the index.html
    tags: apache
    lineinfile:
      path: /var/www/html/index.html
      regexp: '^<p>Ansible is awsome</p>'
      line:  '<p>Ansible is tooooo awsome</p>'
    when: ansible_distribution == "Ubuntu"
    register: diff

  - name: restart apache2
    tags: apache
    service: 
      name: apache2
      state: restarted
    when: diff.changed

  - name: copy default index.html
    tags: apache,apache
    copy:
      src: default_index.html
      dest: /var/www/html/index.html
      mode: 0644
      owner: root
      group: root

- hosts: db-servers
  become: true
  tasks:
    
    - name: install maria db
      tags: db,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: files-servers
  become: true
  tasks:

    - name: install
      tags: samba
      package:
        name: samba
        state: latest

   
  
