- name: install apche in server
  tags: apache,apache2,ubuntu
  package:
    name:
      - "{{apache_package_name}}"
      - "{{php_package_name}}"
    state: latest
  

- name: service apache
  tags: apache
  service:
    name: "{{apache_service}}"
    state: started
    enabled: yes
   
- name: change the index.html
  tags: apache
  lineinfile:
    path: /var/www/html/index.html
    regexp: '^<p>Ansible is awsome</p>'
    line:  '<p>Ansible is tooooo awsome</p>'
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache

- name: copy default index.html
  tags: apache,apache
  copy:
    src: default_index.html
    dest: /var/www/html/index.html
    mode: 0644
    owner: root
    group: root
