---

- hosts: all
  become: true
  pre_tasks:

  - name: update cache
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true   
  roles:
    - prerequsite

- hosts: pgmaster
  become: true
  roles: 
    - pg_master

- hosts: pgslave
  become: true
  roles: 
    - pg_slave

